services:
  grants-payment-floci:
    image: hectorvent/floci:1.1.0
    ports:
      - '4569:4566' # Floci Gateway
      - '4570-4619:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Floci DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      FLOCI_HOST: grants-payment-floci
      MONITOR_SQS: ${MONITOR_SQS:-true}
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:4566']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  floci-init:
    image: amazon/aws-cli
    entrypoint: /bin/sh
    command: /setup/start-floci.sh
    depends_on:
      grants-payment-floci:
        condition: service_healthy
    env_file:
      - 'compose/aws.env'
    volumes:
      - ./compose/start-floci.sh:/setup/start-floci.sh
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27018:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  grants-payment-service:
    build:
      context: .
      target: development
    ports:
      - '3557:3557'
    links:
      - 'grants-payment-floci:grants-payment-floci'
      - 'mongodb:mongodb'
    depends_on:
      grants-payment-floci:
        condition: service_healthy
      floci-init:
        condition: service_completed_successfully
      mongodb:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3557
      NODE_ENV: development
      FLOCI_ENDPOINT: http://grants-payment-floci:4566
      MONGO_URI: mongodb://mongodb:27017/
    networks:
      - cdp-tenant
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json

################################################################################

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
